### ISSUE TITLE
I try this but I  needed to comment six lines and now I need help to create google-services.json same as yours

### ISSUE THREAD

**Issue by neuberfran** [zolkiBy/SimpleBelNewsReader#1]
issues:
![captura de tela 2017-11-23 as 10 00 51](https://user-images.githubusercontent.com/7308528/33185157-941aaf8a-d035-11e7-88e2-bb15bb35a8ca.png)

**Comment by zolkiBy** [comment]
Lines, that you commented, uses to add Youtube API key. Create your own key  and add this key in file project.properties. This file must  be at root project directory. 
Create your own google-services.json and add to project

**Comment by neuberfran** [comment]
thank you. I would very much like you to send me your table and firebase field names to help create a firebase part
